# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76596d2e0e2b64120e4114d19f24342af8ddb6130a2734f9d0e024747b5bfe28284fd1a995fb39f3fa6fd92959f168a197fc566e65a9727e0954e2acee89b966


test:
  secret_key_base: 8c9e36e2b75ccb2834a18481a61f2326e243c621f59114c9dec154a737de5e32b5deb981645cf234828e8bfc630c411db66d409e03dddc63d36e522bf36f1edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
